import { Card, CardHeader, CardTitle, CardDescription } from "./ui/card";
import { Bot, University, Search } from "lucide-react";

const features = [
    {
        icon: <Bot className="w-8 h-8 text-primary" />,
        title: "AI Summarization",
        description: "Get quick summaries and key notes from long documents, generated by AI.",
    },
    {
        icon: <University className="w-8 h-8 text-primary" />,
        title: "University-wise Sorting",
        description: "Easily find resources from your university, department, and semester.",
    },
    {
        icon: <Search className="w-8 h-8 text-primary" />,
        title: "Smart Search",
        description: "Our intelligent search helps you find the exact materials you need in seconds.",
    }
]

export function FeaturesSection() {
  return (
    <section id="about" className="container mx-auto px-4 py-16 md:py-24 bg-background">
      <div className="text-center mb-12">
        <h2 className="text-3xl md:text-4xl font-bold font-headline">Features Built for Students</h2>
        <p className="text-lg text-muted-foreground mt-2">Everything you need to succeed in your studies.</p>
      </div>
      <div className="grid md:grid-cols-3 gap-8">
        {features.map((feature) => (
            <Card key={feature.title} className="text-center hover:shadow-lg transition-shadow duration-300 transform hover:-translate-y-1">
                <CardHeader>
                    <div className="mx-auto bg-primary/10 rounded-full p-3 w-fit mb-4">
                        {feature.icon}
                    </div>
                    <CardTitle className="font-headline">{feature.title}</CardTitle>
                    <CardDescription className="pt-2">{feature.description}</CardDescription>
                </CardHeader>
            </Card>
        ))}
      </div>
    </section>
  );
}
